services:
  - type: web
    name: kenan-gift-ideas
    runtime: node
    buildCommand: "cd client && npm install && npm run build && cd ../server && npm install"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
